version: "3"

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-net
    depends_on:
      - docker
  docker:
    image: docker:18.03.1-ce-dind
    privileged: true
    command: ["--storage-driver=overlay2"]
    volumes:
      - docker_lib:/var/lib/docker
      - cache:/cache
      - builds:/builds
    networks:
      jenkins-net:
        aliases:
          - host.docker.jenkins

networks:
  jenkins-net:

volumes:
  jenkins_home:
  builds:
  cache:
  docker_lib:
