version: "3"

services:
  manager:
    image: docker:18.03.1-ce-dind
    privileged: true
    command: ["--storage-driver=overlay2"]
    volumes:
      - docker_lib:/var/lib/docker
      - cache:/cache
      - builds:/builds
    networks:
      swarm-net:
        aliases:
          - host.manager.swarm
  worker:
    image: docker:18.03.1-ce-dind
    privileged: true
    command: ["--storage-driver=overlay2"]
    volumes:
      - docker_lib_staging:/var/lib/docker
      - cache_staging:/cache
      - builds_staging:/builds
    networks:
      swarm-net:
        aliases:
          - host.worker.swarm
  load-balancer:
    build: .
    ports:
      - "8082:80"
    networks:
      swarm-net:
        aliases:
          - host.load-balancer.swarm

networks:
  swarm-net:
    external:
      name: jenkins_network

volumes:
  builds:
  cache:
  docker_lib:
  docker_lib_staging:
  cache_staging:
  builds_staging:
